### ISSUE TITLE
updateServerToken "infinite loop"

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#100]
When making some bigger amount of changes (seems 201+ new objects is quite enough), I noticed, that updateServerToken method keeps calling itself - it seems operations returns the same changeToken and moreComing flag is yes. Possible steps to reproduce with a sample app :
- delete recordZone zone in cloudkit, delete ios sample app, build it freshly (that there will be no data). 
- synchronize with cloudkit empty db (by clicking synchronize on the left top corner)
- create some more than 200 objects (for example companies). For that I modified insertCompany() method, that it would create 205 companies with one click: 
```    func insertCompany(name: String) {
        for n in 1...205 {
            let company = NSEntityDescription.insertNewObject(forEntityName: "QSCompany", into: managedObjectContext) as! QSCompany
            company.identifier = UUID().uuidString
            company.name = name+"\(n)"
        }
        try? managedObjectContext.save()
    }
``` 
- click the synchronize button again and syncing gets stuck in the updateTokens method:
```
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld insertions" 205
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld updates" 0
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld deletions" 0
"CloudKitSynchronizer >> Initiating synchronization"
"QSCloudKitSynchronizer >> Uploaded 200 records"
"QSCloudKitSynchronizer >> Uploaded 5 records"
"updateTokens: " Optional(<CKServerChangeToken: 0x60000298e5a0; data=AQAAAAAAAAACf/////////+/Qj2GyohLzas0ntPhk9/M>) Optional(<CKServerChangeToken: 0x60000298e310; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>)
"updateTokens: " Optional(<CKServerChangeToken: 0x6000029ab870; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>) Optional(<CKServerChangeToken: 0x6000029a0480; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>)
"updateTokens: " Optional(<CKServerChangeToken: 0x6000029986a0; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>) Optional(<CKServerChangeToken: 0x6000029ab870; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>)
"updateTokens: " Optional(<CKServerChangeToken: 0x60000298e900; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>) Optional(<CKServerChangeToken: 0x60000298e650; data=AQAAAAAAAADKf/////////+/Qj2GyohLzas0ntPhk9/M>)
...
```
I added a debugPrint line before saving change token for the adapter:
`debugPrint("updateTokens: ", adapter?.serverChangeToken, result.serverChangeToken)`

As you can see the same change token (just with the different address) is being saved continuously. After restarting the app, it seems to finish syncing, but I suppose it should somehow deal with such "loop" without a need of restarting the app..

**Comment by mentrena** [comment]
It looks like a bug in the library rather than CloudKit, the token was being saved to the adapter but the old one was still being used for the next call. Just pushed a fix for this to the fixes branch.
