### ISSUE TITLE
crash when disconnecting cloudKitSynchronizer

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#104]
Most apps allows users to work offline (disconnect from cloud kit sync and work with a local data). I suppose SyncKit should also allow that (seems that there are methods for disconnecting/cancel synchronization, erase local data, etc.). However, I cannot make it work 100%, it sometimes crashes (in some completion handler when accessing privatecontext). I suppose taking sync offline should be something like that: 
```
            privateSynchronizer.cancelSynchronization()
            privateSynchronizer.eraseLocalMetadata()
```
Is this the correct way? Should anything else be called? eraseLocalMetadata() calls adapter's deleteChangeTracking(), but adapter seems to be still alive and if synchronization is in progress, some method that tries to access privateContext is being called and app crashes. So, what is the correct way to stop synchronization, destroy synchronizer (and other SyncKit helper objects)?

**Comment by mentrena** [comment]
The sample project has been updated along with `0.7.9` to show how this could be done in an app.

**Comment by BlixLT** [comment]
Thanks for updating the sample app. However, for me it seems, that this issue still exists. I agree, if you sync only few records (what this sample app usually does), then there is no problem - you will (very likely) not be able to trigger disconnect while sync is still in progress, because sync finishes very fast. 

I pulled your updated project, made one slight adjustment to "keep synchroniser busy" when trying to disconnect it:
```
    func insertCompany(name: String) {
      for n in 1...1000 {
        let company = NSEntityDescription.insertNewObject(forEntityName: "QSCompany", into: managedObjectContext) as! QSCompany
        company.identifier = UUID().uuidString
        company.name = name + String(n)
      }
      try? managedObjectContext.save()
    }
```
Then I created 1000 companies with 1 "add company" button click, clicked synchronise, then right away went to settings tab ant turned off sync. After few seconds application crashed in the CoreDataAdapter.didUpload() method. It tried to access privateContext (which I think was destroyed during disable sync process) with an exception "Unexpectedly found nil while implicitly unwrapping an Optional value". So, it looks like nothing changed - when syncing more than several changes, synchroniser still crashes when trying to disconnect. And it is quite easily reproducible with your updated project. Just some bigger number of changes needs to be synced.
Any thoughts on this?

**Comment by mentrena** [comment]
I'm afraid I can't reproduce the issue you describe. I create 1000 company objects the way you do, and disable synchronisation during the sync process, but the app doesn't crash.
Is there anything else you are doing?

**Comment by BlixLT** [comment]
Hm, strange. For me this crash still quite easily reproduces. Let me update the steps and lets see if you will be able to reproduce then:
1) make sure you have 1000 companies locally. I used modified addCompany method (written above) for doing that
2) delete cloudKit zone (this may be done using Erase CloudKit data option in the settings view).
3) make sure Syncing is enabled in the app's settings view. Go to Private tab, click the synchronize button. Then right after doing that, go back to the settings view and disable syncing.

I cannot say, that crash happens 100% every time, but very often. At least 8/10 or so. So, if it doesn't crash, can you try several times these steps. Let me know if it still disconnects normally (without any crash for you). For me it crashes after some time when coredataadapter tries to access privateContext (that I suppose is destroyed during disconnect/disable sync) in some method (most often in the  `public func didUpload(savedRecords: [CKRecord]) {`)

**Comment by mentrena** [comment]
Ok, I had started with a fix that actually worked, so when I tried to reproduce I needed to do a clean build to make it break again.
I guess I'll make `eraseLocalMetadata()` also call `cancelSynchronization()` to cancel any ongoing operations, but you could also call that function yourself before calling `eraseLocalMetadata()` in your app.

**Comment by BlixLT** [comment]
Thanks for the update. Works better now. Its not so easy to crash when disconnecting, but still sometimes happens (1 out of 15 times or so) with similar steps: now you have to synchronize when there is alrady data on iCloud - enable syncing, keep data, click synchronize, disable. It seems that some code is being executed even after operation is cancelled, but as I said it happens rarely. I will add logs, maybe it will help:
```
"CloudKitSynchronizer >> Initiating synchronization"
"QSCloudKitSynchronizer >> Downloaded 200 changed records >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"QSCloudKitSynchronizer >> Downloaded 0 deleted record IDs >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"Save changes in records"
"Applying attribute changes in records"
"QSCloudKitSynchronizer >> Downloaded 200 changed records >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"QSCloudKitSynchronizer >> Downloaded 0 deleted record IDs >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"Save changes in records"
"Applying attribute changes in records"
"QSCloudKitSynchronizer >> Downloaded 159 changed records >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"QSCloudKitSynchronizer >> Downloaded 0 deleted record IDs >> from zone <CKRecordZoneID: 0x600001eeffa0; ownerName=__defaultOwner__, zoneName=QSCloudKitCustomZoneName>"
"Save changes in records"
"Applying attribute changes in records"
"Target apply pending relationships"
"Requesting save"
"Now importing"
"Saved imported changes"
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld insertions" 0
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld updates" 0
"QSCloudKitSynchronizer >> Did Save >> Tracking %ld deletions" 0
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/user/cocoa/test/SyncKit_original/SyncKit/Classes/CoreData/CoreDataAdapter+ModelAdapter.swift, line 140
2020-01-27 11:19:47.395082+0200 SyncKitCoreDataExample[5248:404411] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/user/cocoa/test/SyncKit_original/SyncKit/Classes/CoreData/CoreDataAdapter+ModelAdapter.swift, line 140
```
didUpload() method (line 140). is being called and privateContext is nil there. But it happens not so often and I cannot find a pattern yet.

**Comment by BlixLT** [comment]
One more crash happens when you enable synchronization and choose not to keep data. This seems to happen 100% of the time. Not sure if I should create a new issue as it is related with enable synchronization, not with disconnection. Right now I will just post here:
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/cocoa/test/SyncKit_original/SyncKit/Classes/CoreData/CoreDataAdapter+Private.swift, line 95
2020-01-27 12:04:05.177981+0200 SyncKitCoreDataExample[6084:524245] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/cocoa/test/SyncKit_original/SyncKit/Classes/CoreData/CoreDataAdapter+Private.swift, line 95
```
It seems that deleteAll triggers targetContextWillSave, that tries to get uniqueIdentifier for the object, but entityPrimaryKeys is empty at that time. Maybe it should be created before observing willsave notifications. Or objects should be deleted earlier - before CoreDataAdapter is observing will save notifications.
