### ISSUE TITLE
Is there any way to set primary key Int?

### ISSUE THREAD

**Issue by sambong0113** [mentrena/SyncKit#116]
I'm using primary key to id type of Int64.
If that it return nil because of failing String converting.

Is there any way to use primary key type of Int?

**Comment by mentrena** [comment]
Not as such, but you could just do

```swift
@NSManaged public var identifier: Int? // The Int identifier you're using

@objc public var identifierAsString: String? { // A computed property to transform Int<->String
    get {
        return identifier != nil ? String(identifier!) : nil
    }
    set {
        identifier = newValue != nil ? Int(newValue) : nil
    }
}

public static func primaryKey() -> String {
        return "identifierAsString"
    }
```

**Comment by sambong0113** [comment]
I just try that code, but it returns nil error in that function.
<img width="838" alt="스크린샷 2020-03-28 오후 4 03 27" src="https://user-images.githubusercontent.com/36813712/77817360-ab428b80-710d-11ea-99bb-ee13c28450ec.png">

The originalObject is nil because of NSPredicate fail.

Is there any possible way to fix it?

**Comment by mentrena** [comment]
Ah right, can't fetch on a computed property :/

I think it would be possible to support Int identifiers as well, but if you want to use the library in the meantime you would have to add a String type identifier to your objects.
