### ISSUE TITLE
Synchronize speed up

### ISSUE THREAD

**Issue by sambong0113** [mentrena/SyncKit#118]
I wonder is there any way to speed up of synchronizer.

Because I apply this synchronizing after many months app launching, people have many data.

So it's too slow to upload & download datas.

I saw the batchSize and change value but it doesn't work.

And I wonder when I end app while downloading records, how to continue after I downloaded data?

**Comment by mentrena** [comment]
> Because I apply this synchronizing after many months app launching, people have many data.

Data will only be uploaded/downloaded if it's been changed. So it's not a matter of how much data users have, but how much data they periodically change. If your users are updating their data then it has to be sent to CloudKit, there's no other way to keep it synchronized.
In your app you should be careful to not change data unnecessarily.

> And I wonder when I end app while downloading records, how to continue after I downloaded data?

If the app gets terminated for any reason while downloading data and before that data gets saved to disk, then that data will need to be downloaded next time you launch the app.
It should be as simple as initiating synchronisation again.
