### ISSUE TITLE
QSTempFilemanager deletes files when sharing/removing share

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#120]
QSTempFilemanager deletes its used files when `CoreDataAdapter.didFinishImport()` is called. This is done in 3 places - `CloudKitSynchronizer.finishSynchronization()`, `CloudKitSynchronizer.share(object: AnyObject,...)` and `CloudKitSynchronizer.removeShare(for object: ...)`. 
All 3 operations are async, so several of them may be executed at the same time - for example, synchronization of some bigger number of objects happens (upload happens in batches, so several modifyRecordsOperations will be created) and you call CloudKitSynchronizer share(object:...). The latter uploads only 2 objects - an object that is being shared and its CKShare, so its modifyRecordsCompletion handler will be called earlier than ongoing synchronization operation and it will clear QSTempFilemanager files - however they might be still needed by synchronization operation. And therefore modifyRecordsOperation might fail with CKAsset file not found error. 
I suppose it would be perfect if QSTempFilemanager deleted files per modifyRecordsOperation - only these that were used there, but not all folder. Not sure how to implement it so easily. Another not so elegant solution would be delete files only after synchronization is finished, but leave it when didFinishImport is being called from share() or removeShare(). Just some thoughts. Maybe you have other ideas how to fix this.

**Comment by mentrena** [comment]
0.7.12 prevents sharing objects while the library is syncing, it's up to the application to coordinate this.
