### ISSUE TITLE
Full watchOS 6 support

### ISSUE THREAD

**Issue by martindaum** [mentrena/SyncKit#122]
CKSubscription is available for watchOS starting at 6.0. It would be cool if SyncKit would support this as well!

**Comment by mentrena** [comment]
Hi Martin, can't say I test much on watchOS but I guess this is all that's needed?
https://github.com/mentrena/SyncKit/pull/121/commits/3e9f25be995b4e179187af89c5a1b1eb2222df73

**Comment by martindaum** [comment]
I guess so, that is basically what I did to test it. Testing CloudKit on Apple watch is horrible, but we have to for our app. I can keep you updated if the subscriptions work. When do you have planned to make a release including this fixes? I will use your branch for now!

**Comment by mentrena** [comment]
0.7.12 is published, I'll close here but feel free to reopen if you find any issues.
