### ISSUE TITLE
Carthage integration not working with Swift 5.2.2

### ISSUE THREAD

**Issue by martindaum** [mentrena/SyncKit#123]
I get the following error when I try to install SyncKit with Carthage (Xcode 11.4.1):
module compiled with Swift 5.0.1 cannot be imported by the Swift 5.2.2

This might require an update of the realm frameworks included in this repository?

**Comment by fm3108** [comment]
We have the same issue: 

carthage update --platform iOS
*** Fetching SyncKit
*** Checking out SyncKit at "0.7.12"
*** xcodebuild output can be found in /var/folders/g1/yc1_4jpd0qd6ptdlvpp1qp8w0000gp/T/carthage-xcodebuild.LMi30T.log
*** Building scheme "SyncKitCoreDataiOS" in SyncKitCoreData.xcworkspace
*** Building scheme "SyncKitRealmiOS" in SyncKitRealm.xcworkspace
*** Building scheme "SyncKitRealmSwiftiOS" in SyncKitRealmSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/frank.moller/projects/native/mein-team/Carthage/Checkouts/SyncKit/Example/RealmSwift/SyncKitRealmSwift.xcworkspace -scheme SyncKitRealmSwiftiOS -configuration Release -derivedDataPath /Users/frank.moller/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/SyncKit/0.7.12 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/g1/yc1_4jpd0qd6ptdlvpp1qp8w0000gp/T/SyncKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/frank.moller/projects/native/mein-team/Carthage/Checkouts/SyncKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/g1/yc1_4jpd0qd6ptdlvpp1qp8w0000gp/T/carthage-xcodebuild.LMi30T.log

**Last line in the compiler log:**

.../Carthage/Checkouts/SyncKit/SyncKit/Classes/RealmSwift/PendingRelationship.swift:10:8: error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.2.2 compiler: /Users/frank.moller/projects/native/mein-team/Carthage/Checkouts/SyncKit/Example/RealmSwift/SyncKitRealmSwiftiOS/SyncKit/RealmSwift.framework/Modules/RealmSwift.swiftmodule/armv7.swiftmodule
import RealmSwift

**Any plans to solve this issue?**

**Comment by mentrena** [comment]
Should hopefully be fixed now with 0.7.13.

**Comment by fm3108** [comment]
Hi Manuel, thanks for the quick response! It's fixed!
