### ISSUE TITLE
synchronization's completion might be overwritten

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#124]
It looks like there is not so small gap in the `finishSynchronization` method between  lines `syncing = false` and execution of that synchronization's completion. IMO It is possible, that before `self.completion?(error)` is actually executed, a new completion will be set in the `public func synchronize(completion: ((Error?) -> ())?) {`

At least this is what I experiencing sometimes. I think the main cause of this is this code in the  `func finishSynchronization(error: Error?) {` :
```
...
for adapter in modelAdapters {
adapter.didFinishImport(with: error)
}
...
```

as far as I understand, adapter's privateContext might be in the context's block processing targetcontext's will/did save notifcations and updating local cache (that could cause adapterHashanges = true). So, for example main app might observe adapterHasChangesNotification and call synchronizer's synchronize() method before previous synchronization's completion is called. (Or just might accidentally trigger/call synchronize() at that moment). And previously set completion will be lost, because `func synchronize(completion: ((Error?) -> ())?)` will set a new completion. Not sure if I was fluent enough, I hope you understood the problem. 
I wonder is there a reason why `syncing = false` and `cancelSync = false` is being called so early in the `finishSynchronization`. For me it looks like it would be better to set `syncing = false` at least after all adapter's `didFinishImport`. Unless these flags need to be set that early due to some SyncKit logic, that I am not aware of/missing.

**Comment by mentrena** [comment]
Fix in https://github.com/mentrena/SyncKit/pull/132
