### ISSUE TITLE
Potential crash when adding an object with existing primary key

### ISSUE THREAD

**Issue by martindaum** [mentrena/SyncKit#126]
For our app it could happen that two clients send an object with the same primary key, because that id is generated using a timestamp.

This could be resolved by changing:
`realmProvider.targetRealm.add(object)`
to
`realmProvider.targetRealm.add(object, update: .modified)`
In RealmSwiftAdapter.swift. 

I don't know if this has any unwanted side effects, but for us it would resolve the crash caused by the exception thrown by Realm whenever an object is added for an existing primary key.

**Comment by mentrena** [comment]
That change should not be necessary, if the same object already exists in two devices A and B, when A uploads it and B downloads it, B would update its object, not attempt to create a new one with the same ID –which would indeed fail.
When B downloads the record it finds an existing object with the given ID, so it uses that one.

There might be some other reason I haven't considered, what is the sequence that causes the crash in your app?
