### ISSUE TITLE
deleteInsertedButUnmergedEntities wrong implementation?

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#127]
objective-c 0.6.x version looked like this:
```
- (void)deleteInsertedButUnmergedEntities
{
    NSArray *pendingEntities = [self entitiesWithState:QSSyncedEntityStateInserted];
    for (QSSyncedEntity *pending in [pendingEntities copy]) {
        [self.privateContext deleteObject:pending];
    }
}

```
now (swift version) does this:
```
    func deleteInsertedButUnmergedEntities() {
        let pendingEntities = fetchEntities(state: .inserted)
        pendingEntities.forEach {
            $0.entityState = .synced
        }
    }
```
It looks like that it acts the same as updateInsertedEntitiesAndSave, just without save. At the first glance it seems like a bug (or copt/paste from a similar method), but maybe SyncKit logic changed (when/after rewritting on swift) and it does what it should here.

**Comment by mentrena** [comment]
Fixed on https://github.com/mentrena/SyncKit/pull/132
