### ISSUE TITLE
Missing data when accepting share for the 2nd time

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#128]
Something is wrong with shared db synchronizer's logic. Looks like it cannot work the same as private db synchronizer. Lets say userA created companyA, added EmpoyeeA, EmployeeB to it and shared to userB. UserB sees companyA (with EmpoyeeA and EmployeeB). userB adds EmployeeC to it. Both - owner (userA) and userB sees all 3 emplyees. UserA stops sharing account -> it disappears from userB shared db. UserA shares it again to userB, userB accepts it, but only EmployeeA and EmployeeB are being downloaded by SyncKit this time. EmployeeC is being ignored (because last change was made on userB device and that change is being ignored).

**Comment by BlixLT** [comment]
The best solution I could come up with is to reset deviceIdentifier/deviceUUID when accepting any? share. That way these changes (when accepting previously accepted/left share) would not be ignored. Not the ideal solution, but I suppose it should work.

**Comment by BlixLT** [comment]
Apparently my suggestion does not work: If you have more than 1 device, accept that share for the second time on 1 of them, the other one(s) downloads records/changes of that share, but ignore changes that were previously made on that device. So, resetting device identifier might work (= probably fix this issue) only on device that is accepting share for the second time, but all other that user's devices will ignore some changes (the ones that were made on these devices before leaving a share). Any ideas what can be done here?

**Comment by aehlke** [comment]
did you find the logic in this codebase?

**Comment by mentrena** [comment]
This should be fixed in 1.3.2, thanks!
