### ISSUE TITLE
Make it available for Watch OS

### ISSUE THREAD

**Issue by spotlessicode** [mentrena/SyncKit#13]
Hi, 

Could you make it (the pod file) available for Watch OS too? Watchkit Extension has a separate Core Data stack but with the same model and CloudKit Framework available too, so we could use it on that device too. I think so the integration is the same as at the IOS side.  So that would be really great!

Thank you!

**Comment by mentrena** [comment]
I'm not that familiar with WatchOS, is it fully compatible with both CoreData and CloudKit?
Is it just a matter of updating the pod spec? :)

**Comment by spotlessicode** [comment]
Yes you can set up the same CoreData as in the IOS or Mac side. And CloudKit.framework is available for Watch OS (3 or higher) too. Apple uses CloudKit with every App on every platform (tvOS, Watch OS, IOS, MacOS and web too). At WatchOS there is a Watch Connectivity framework, which helps to communicate between IOS and WatchKit, but that about relevant fresh must to see data, not for the whole database. 
Yes I think you should just update the pod spec. I would like to implement SyncKit for Watch OS in these days (after I solved my issue), So if it needs some more code or steps to implement, I share it of course. Just please update the pod for that. 
Thank you!

**Comment by mentrena** [comment]
It seems WatchOS supports CloudKit, but only the modern API (available on iOS 10).
SyncKit still uses the original CloudKit API, as it supports iOS 8+.
It probably makes sense to drop support for iOS 8 and iOS 9 in future versions and adopt the new methods, and then add support for WatchOS.

**Comment by spotlessicode** [comment]
I started this project on IOS10, so I didn't check the changes... But  now I've read, according to Apple Documentation: 

> If your Watch app and iOS app use the same server, it is usually simpler for each process to fetch its data separately rather than trying to sync from one app to the other. If you want to ensure the two apps are synchronized, use the updateApplicationContext:error: method to communicate basic information such as record IDs or title strings so that each app knows what the other has fetched.

**Comment by spotlessicode** [comment]
[SyncKit To WatchKit](https://github.com/spotlessicode/SyncKitToWatchKit)

- IOS sync with CloudKit
- Watch OS download Data from CloudKit
- Watch OS data changes sent to IOS with WatchConnectivity
- IOS get data form WatchOS & save changes & sync with CloudKit, & notify WatchOS that it could download again - so the user can make changes on Watchos without new CloudKit download.

**Comment by mentrena** [comment]
So it's working after you removed all the references to CKSubscription?

**Comment by spotlessicode** [comment]
Hi, sorry I was on a holiday ;) - yes it works, but you need to remove other references too. I need 1 week for other tasks, and I'll upload a full tutorial project for WatchOS with cleared SyncKit files and updated references. After that, I can send you the exact necessary changes. And it will be tested with Xcode 9 IOS 11 and WatchOS 4 too. ;) It already works with Xcode 9 IOS 11 and WatchOS 3.

**Comment by spotlessicode** [comment]
Hi, the answer is yes, everything is fine without `CKSubsription`. **SyncKit** works fully, but I suggest to use at [WatchKit with Download mode](https://github.com/spotlessicode/SyncKitToWatchKit/blob/master/README.md) as I mentioned earlier according to Apple suggestions. (I think with new Watch Series 3 built-in cellular that could  work total separately, and in the future that will be the general mode.. this is the future...). 

I had no time for a full tutorial yet, but in the real App, it works perfectly. As I know Watch OS 4 public version release date is tomorrow, so I will test with that too. And finally at the end of this week or the beginning next week the full tutorial App will be available. 

**Finally, I really recommend to update** the deprecated references as[ I mentioned here](https://github.com/mentrena/SyncKit/issues/20), and make [these changes](https://github.com/spotlessicode/SyncKitToWatchKit/commit/5ec7733e9553f6a29b8a09ef85beddbe389546ac) available just for TARGET_OS_WATCH and updating the pod spec.

**Comment by spotlessicode** [comment]
It works perfectly with Watch OS 4 and IOS 11 public versions on real devices ;) - 0.5.2 (with just removing CKSubscripton and set Download mode at Watch part - without changes of deprecations)  

I really try to create an example App with all settings in the next days, so you can test it too.

**Comment by mentrena** [comment]
`0.5.5` should work on Watch OS as needed (in your case, setting the sync mode to download only)
I think this can be closed, but let me know if more changes are needed.
