### ISSUE TITLE
synchronization stops after uploading 1 batch of deleted objects

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#131]
`func uploadDeletions(adapter: ModelAdapter, completion: @escaping (Error?)->()) {` 
should continue upload deleted objects until all are being uploaded. Now it seems that it stops (finishes synchronizartion) after the first batch.

**Comment by mentrena** [comment]
Added a fix on https://github.com/mentrena/SyncKit/pull/132
