### ISSUE TITLE
SyncKitRealmSwiftiOS fails to build under Xcode 12

### ISSUE THREAD

**Issue by w8wjb** [mentrena/SyncKit#134]
The problem is with the embedded `RealmSwift.framework`:

```error: module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler```

**Comment by mentrena** [comment]
Having some problems publishing the pod, but master has been updated to use the latest Realm, you might be able to use that if you're using Carthage.

**Comment by w8wjb** [comment]
That fixed the Carthage build for me. Thank you!
