### ISSUE TITLE
Get realm of object

### ISSUE THREAD

**Issue by torfluor** [mentrena/SyncKit#137]
In my application I have a tableview that contain objects from both the private and shared database. To make this work I have a list item class that holds a property with the primary key of the object. As I don't know which realm the object is located I can't use `realm?.object(ofType: CompanyModel.self, forPrimaryKey: id)` directly. I have to find which realm the object is located in first.
I have solved this by setting the realms property in DefaultRealmProvider.swift to public in my fork of SyncKit and creating the lookup method below. This is a hack and it would be great if there was an official way of getting the realm based on a primary key.

    var privateRealm: Realm
    private var realmCache = [String: Realm]()
    
    public func realmForCompanyModelId(id: String) -> Realm? {
        
        if let realm = realmCache[id] {
            return realm
        }
        
        // Check private realm first
        if privateRealm.object(ofType: CompanyModel.self, forPrimaryKey: id) != nil {
            realmCache[id] = privateRealm
            return privateRealm
        }
        
        // Check shared realms
        if let provider = sharedSynchronizer.adapterProvider as? DefaultRealmProvider {
            // I had to make the realms property public to get this to work
            for configuration in provider.realms.values {
                if let realm = try? Realm(configuration: configuration) {
                    if realm.object(ofType: CompanyModel.self, forPrimaryKey: id) != nil {
                        realmCache[id] = realm
                        return realm
                    }
                }
            }
        }
        return nil
    }
   `

**Comment by mentrena** [comment]
Realm objects have a `public var realm: Realm?` property. 
See:
https://github.com/realm/realm-cocoa/blob/7915e1c760874bb6ba967590d687a8fd6021db96/RealmSwift/Object.swift#L107

**Comment by torfluor** [comment]
Sorry, I didn't explain my problem very well. I have updated the question now. What I need is a method to get an object based on the primary key without knowing which realm it belongs to.

**Comment by mentrena** [comment]
Have you checked `MultiRealmResultsController`?
You could do something like:
```swift
let controller: MultiRealmResultsController<YourType> = sharedSynchronizer.multiRealmResultsController()
// Use controller.results to list objects
// Find a specific object
let object = controller.results.first { $0.primaryKeyProperty == id }
```

In the Example project I use it in https://github.com/mentrena/SyncKit/blob/fd24289dc213d3c2b95ab8fd746c0017e61e6b57/Example/RealmSwift/SyncKitRealmSwiftExample/SyncKitRealmSwiftExample/Company/Realm/RealmSharedCompanyInteractor.swift#L13

to take objects that could be coming from different realms (CloudKit shared zones) and provide a single list that can be used in the UI.

Let me know if that works, otherwise I imagine I could make that property public in the realm provider, but ideally you wouldn't need to dig that deep to get what you need.

**Comment by torfluor** [comment]
I have tried the MultiRealmResultsController but I didn't get it to work with objects from both the private and the shared realms. 

I will give you some more background of my project. The app is a kind of document app, where the users can create and share documents called timelines. To complicate things even further, the timeline can be grouped into folders. As Realm can't have queries that return objects of more than one kind (folders and timelines) I have made a FolderItemModel which have links to either a folder or a timeline. The FolderItemModel objects are always located in the private realm. As timelines can be located in either the private or shared realms I can't store the TimelineModel directly in the FolderItemModel, so I store the public key instead. This is why I want to get the object from the public key. If you have any ideas on how I can solve this in a more elegant way I would be forever grateful :) 

    class FolderItemModel: Object {
        @objc dynamic var id: String = UUID().uuidString
        @objc dynamic var sortIndex: Int = 0
        @objc dynamic var inFolder: TimelineFolderModel?
        @objc dynamic var timelineModelId: String?
        @objc dynamic var folderModel: TimelineFolderModel?
    
        override static func primaryKey() -> String? { return "id" }
        [...]
    }
    
    class TimelineFolderModel: Object {
        @objc dynamic var id: String = UUID().uuidString
        @objc dynamic var title: String = ""
        @objc dynamic var partOfFolderItem: FolderItemModel?
        let folderItems = LinkingObjects(fromType: FolderItemModel.self, property: "inFolder")
        override static func primaryKey() -> String? { return "id" }
    }
![mainPage](https://user-images.githubusercontent.com/38349756/99255364-1f07e480-2814-11eb-86e8-a67b00af14cc.PNG)

**Comment by mentrena** [comment]
MultiRealmResultsController is intended to give you access to all objects of one type from one synchronizer.
The private realm is fully owned by you so you're better off just accessing it directly the way you're doing it now. For objects shared with you a results controller can make it easy to access them without having to worry about exactly how many realms have been created internally to store those objects.
I think your initial code could be tweaked like this (assuming an object of type Timeline):

```swift
var privateRealm: Realm
private var realmCache = [String: Timeline]()
private var sharedTimelineResultsController: MultiRealmResultsController<Timeline> = sharedSynchronizer.multiRealmResultsController()

...

sharedTimelineResultsController.didChangeRealms = { _ in
    // A realm was added (a share was accepted from a new user) or deleted (access to a share was removed for this user), so this should trigger a refresh
}

...

// Find the Timeline object for an id, looks first in the private data, then in the data shared with this user
public func realmForCompanyModelId(id: String) -> Timeline? {
    
    if let timeline = realmCache[id] {
        return timeline
    }
    
    // Check private realm first
    if let timeline = privateRealm.object(ofType: Timeline.self, forPrimaryKey: id) {
        realmCache[id] = timeline
        return timeline
    }
    
    // Check shared realms
    if let timeline = sharedTimelineResultsController.results.first(where: { $0.timelineId == id } {
        realmCache[id] = timeline
        return timeline
    }
    
    return nil
}
```

So you still need to query by id, but this query uses sharedTimelineResultsController.results, which gives you all the timelines that have been shared with the current user. 
This should work for you right now, but I'm thinking it would be worth it to extend MultiRealmResultsController to allow querying by id, not just by predicate, it might give better performance if there is a huge number of objects.

**Comment by torfluor** [comment]
That solved my issue. Thank you so much!
I don't expect my lists of shared timeline will be large, but being able to query MultiRealmResultsController by id sound like a good idea.
Thanks again!
