### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by hennessyevan** [mentrena/SyncKit#141]
Is it possible to add swift package manager support for this project?

If I can figure it out I'll definitely submit a PR for this, I just wanted to know if there was some technical reason for not supporting it as of yet.

**Comment by mentrena** [comment]
I just haven't used SPM yet so I never looked into this, but you would certainly be welcome to add support for it :)

**Comment by mentrena** [comment]
This has now been added in `1.0.0`

**Comment by hennessyevan** [comment]
🙌🏻
