### ISSUE TITLE
Is there a way to know what changed after a synchronization?

### ISSUE THREAD

**Issue by MilesV64** [mentrena/SyncKit#142]
After calling synchronizer.synchronize(), is there a way to see what models were added/updated/removed to efficiently update the UI of various sections of an app?

**Comment by mentrena** [comment]
SyncKit doesn't explicitly return changed models, instead you can use the native Core Data or Realm mechanisms to detect changes.
In my Core Data apps I use NSFetchedResultsController, and for Realm apps I use Realm notifications (https://realm.io/docs/swift/latest/#collection-notifications)

The example project also uses those:
[CoreDataCompanyInteractor.swift](https://github.com/mentrena/SyncKit/blob/master/Example/CoreData/SyncKitCoreDataExample/SyncKitCoreDataExample/Company/CoreData/CoreDataCompanyInteractor.swift)

[RealmCompanyInteractor](https://github.com/mentrena/SyncKit/blob/master/Example/RealmSwift/SyncKitRealmSwiftExample/SyncKitRealmSwiftExample/Company/Realm/RealmCompanyInteractor.swift)

**Comment by MilesV64** [comment]
Great, thanks! Is there a way to differentiate a Realm model update from synchronizing vs a model update from Realm.write? For example, would all updates be sure to occur before the synchronizer finishes and therefor you could just check if the synchronizer is running, or schedule the detector before and unschedule it in the callback?

**Comment by mentrena** [comment]
For Realm I don't think it would be guaranteed.

Actually, have a look at implementing [RealmSwiftAdapterRecordProcessing:shouldProcessPropertyInDownload](https://github.com/mentrena/SyncKit/blob/78fbb3639ceb8110087dbcf49141d104a98c939a/SyncKit/Classes/RealmSwift/RealmSwiftAdapter.swift#L59)

That method gives you a chance to process downloaded records yourself. You could just use it to detect which objects are being changed –and return true so SyncKit still processes those changes normally.

**Comment by MilesV64** [comment]
That looks perfect actually! Thanks for your help.
