### ISSUE TITLE
Support for integer primary key in RealmSwift

### ISSUE THREAD

**Issue by sskjames** [mentrena/SyncKit#147]
Hi @mentrena and others, first of all thank you very much for this library.
I'm trying to use SyncKit with our app and found that SyncKit doesn't support integers as primary key currently. (Ref: #116)
Can it be supported? All the primary keys in my Realm models are all integers. 
It would be great if this feature can be supported. 

Thanks in advance, 
James

**Comment by sskjames** [comment]
Hi @mentrena, would it be possible to support integer primary keys?
The project that I work on currently has mostly integer primary keys for the entities.

**Comment by mentrena** [comment]
Hi @sskjames, it should be possible. I will look into that next, as time allows.

**Comment by sskjames** [comment]
Hi @mentrena, thank you very much for the response. Thanks for all your effort in maintaining this amazing library.

**Comment by mentrena** [comment]
Just released 1.1.0 with this :)
I did fix a couple of issues that I found while adding extra test coverage, so I'd suggest upgrading the library if you were already using the code from the PR. Thanks!

**Comment by sskjames** [comment]
Thank you. Will test this out.
