### ISSUE TITLE
Update RealmSwift

### ISSUE THREAD

**Issue by worldden** [mentrena/SyncKit#150]
Hello, 

after updating Xcode up to 12.5, we have got a problem with RealmSwift (screenshot).

To solve it, we need to update RealmSwift at least to version 10.5.2. Could you please update RealmSwift in SyncKit/RealmSwift?

Many thanks!

**Comment by worldden** [comment]
<img width="1027" alt="Screenshot 2021-04-28 at 13 05 29" src="https://user-images.githubusercontent.com/38764049/116671027-24fc1700-a9a9-11eb-88fc-29ce3546108b.png">

**Comment by mentrena** [comment]
Thanks for noticing, I've released 1.0.1  with a fix.

**Comment by worldden** [comment]
Many thanks)
