### ISSUE TITLE
Does SyncKit support Zone sharing?

### ISSUE THREAD

**Issue by sskjames** [mentrena/SyncKit#161]
In WWDC 2021, Apple announced the support for [Zone sharing](https://developer.apple.com/videos/play/wwdc2021/10086/). This makes it possible to share records without having to define the "parent".

Does SyncKit support this feature?

**Comment by mentrena** [comment]
I haven't caught up with the 2021 WWDC videos yet so I'm gonna guess no 😅 
But thanks for bringing it up, I'll definitely watch the session soon.

**Comment by mentrena** [comment]
Just to update, I saw the WWDC session and I'm working on adding support for this.

**Comment by mentrena** [comment]
`1.3.0` adds support for this, cheers.
