### ISSUE TITLE
As a participant, how can I remove myself from sharing?

### ISSUE THREAD

**Issue by Mr-ZNN** [mentrena/SyncKit#167]
As a participant, how can I remove myself from sharing?
I try to call 
```
func removeShare(for object: AnyObject, completion: ((Error?) -> ())?)
```
The call as the author can be successful, but the call as the participant is unsuccessful.

**Comment by mentrena** [comment]
What error do you get? Are you using UICloudSharingController or do you use your own UI to manage sharing?
