### ISSUE TITLE
Synchronization from extensions duplicates all records

### ISSUE THREAD

**Issue by Kautenja** [mentrena/SyncKit#17]
I've just stumbled upon an issue where synchronization from extensions (Today Extensions in this case) results in the database being duplicated entirely then synchronized to iCloud. When I check the object IDs of the newly created duplicates they read differently than the originals. Originally the extensions were designed using AppGroups so they could access the same CoreData stack as my application. I wanted the extensions to be able to sync when they load so if new data was generated on another device and not currently synced to the one viewing the extension, it would reload with the new data. The extensions set the `QSCloudKitSynchronizer` to download only, so i'm thinking that when they run they're downloading records and assigning them new objectIDs and storing them in the shared data store. Then whenever the application opens next it synchronizes these new records to CloudKit resulting in the other connected devices downloading the records.

Am I right in interpreting this as a bug or is this an error in my understanding of iOS extensions/SyncKit?

**Comment by Kautenja** [comment]
Hmm this might actually be a duplicate of #16?

**Comment by mentrena** [comment]
Yeah, it's the same issue. Let's continue there.
