### ISSUE TITLE
Variable of type "List<String>()" is not being uploaded.

### ISSUE THREAD

**Issue by 29satnam** [mentrena/SyncKit#170]
Thanks for this library. 
I have this variable in the model `var category = List<String>()`. It's being completely ignored. I went to Record Fields in the CloudKit and can't find it anywhere.
Do we have a workaround to make this work.

**Comment by mentrena** [comment]
Hi @29satnam ,

Properties of type array are not supported, however you could provide a delegate conforming to `RealmSwiftAdapterRecordProcessing` and encode those properties into a record. Something like this:

```swift
let adapter = synchronizer.modelAdapters.first! // Assuming you're using a simple synchronizer with a single model adapter
adapter.recordProcessingDelegate = self // or whichever object will implement the delegate protocol

...

// Then implement

func shouldProcessPropertyBeforeUpload(propertyName: String, object: Object, record: CKRecord) -> Bool {
    if propertyName == "category",
        let yourObject = object as? YourObjectType {
        record["category"] = yourObject.category.joined(separator: ",")
        return false
    }
    return true
}

func shouldProcessPropertyInDownload(propertyName: String, object: Object, record: CKRecord) -> Bool {
    if propertyName == "category",
        let yourObject = object as? YourObjectType {
        let categoryString = record["category"] as? String
        yourObject.category = categoryString?.split(separator: ",") ?? []
        return false
    }
    return true
}
```

**Comment by 29satnam** [comment]
I really appreciate your fast reply! When I upload data the delegate function converts the `category` property to string just fine, but when being downloaded, it just ignores the `category` property and downloads everything else. What am I missing.

**Comment by 29satnam** [comment]
I ended up changing `List<String>()` to just `String`.
