### ISSUE TITLE
Threading logic bug

### ISSUE THREAD

**Issue by aehlke** [mentrena/SyncKit#186]
This function may return nil if called from a non-main thread because it assigns a variable within the dispatch and returns without blocking

https://github.com/mentrena/SyncKit/blob/1a1c0409a1d25b67eb522842a3764442e2a3fbd9/SyncKit/Classes/RealmSwift/RealmSwiftAdapter.swift#L1263

**Comment by mentrena** [comment]
The dispatch is synchronous though, why do you say it's not blocking?

**Comment by aehlke** [comment]
You're probably correct, I spotted this while translating the lib to run in background threads and may have misread

**Comment by aehlke** [comment]
```
    if Thread.isMainThread {
        closure()
    } else {
        DispatchQueue.main.sync {
            closure()
        }
    }
```
synchronous indeed, thank you
