### ISSUE TITLE
Any plans for Swift?

### ISSUE THREAD

**Issue by gtennis** [mentrena/SyncKit#19]
Apple has already added some reflection features in Swift 3 to introspect object structure during runtime. Any plans to make this awesome library available to be used in Swift projects?

**Comment by Kautenja** [comment]
this framework can be used in Swift projects already. check out this example project https://github.com/Kautenja/iOSTodayExtensionUbiquitySampleProject

**Comment by gtennis** [comment]
Any Realm example? I'm trying to make first steps work but getting "_Cannot convert value of type 'Realm.Configuration' to expected argument type 'RLMRealmConfiguration!_'"

```
init() {
        
        do {
            self.realm = try Realm()
            let containerIdentifier = ("iCloud.\(Bundle.main.bundleIdentifier!)")
            self.synchronizer = QSCloudKitSynchronizer(containerName:containerIdentifier, realmConfiguration: self.realm.configuration)
        } catch let error as NSError {
            Logging.error(error.localizedDescription)
        }
    }
```

**Comment by mentrena** [comment]
Hi @gtennis , RealmSwift is not supported at the moment just because the Realm and RealmSwift APIs are not interoperable and I didn't get to do the Swift part yet, but it's definitely on the roadmap.

**Comment by mentrena** [comment]
0.5.2 adds support for RealmSwift.
