### ISSUE TITLE
support latest IOS (10-11) and Watch OS (3-4) versions

### ISSUE THREAD

**Issue by spotlessicode** [mentrena/SyncKit#20]
I have a lot of deprecations and warnings in SyncKit, could you update the library with the most common things? I have summarized them in a list instead of overwriting this git library.

[A recent iOS version stats counter from Apple showing](https://developer.apple.com/support/app-store/) that there are only 11% devices which are still having iOS 9 (9%) or earlier (2%), and 89% of devices have IOS 10. I believe you should drop out support for those versions or if you want to support IOS 9, it should be better a version check, but don't use basically deprecated codes. Watch OS 4 will available at all Watch series, so it is simply not worth supporting older versions than WatchOS 3.0. 

**1. Nullability Issues in Obj-C** - nonnul and nullable **QSChangeManager.h**  file mostly
**2. Deprecations:** 
suggestion: 
`if #available(iOS 9, *) {} `
for:
- `CKOwnerDefaultName` in **QSCloudKitSynchronizer+CoreData.m** - row 43
```Objective-C
CK_EXTERN NSString * const CKCurrentUserDefaultName API_AVAILABLE(macos(10.12), ios(10.0), tvos(10.0), watchos(3.0));
CK_EXTERN NSString * const CKOwnerDefaultName API_DEPRECATED_WITH_REPLACEMENT("CKCurrentUserDefaultName", macos(10.10, 10.12), ios(8.0, 10.0), tvos(9.0, 10.0), watchos(3.0, 3.0));
```
- `CKFetchRecordChangesOperation` in **QSCloudKitSynchronizer.m** - row 494 and 565
```Objective-C
API_DEPRECATED_WITH_REPLACEMENT("CKFetchRecordZoneChangesOperation", macos(10.10, 10.12), ios(8.0, 10.0), tvos(9.0, 10.0), watchos(3.0, 3.0))
```
**one more in QSManagedObjectContext.m** 
```Objective-C
(void)performBlock:(void(^)())block
{
    [self performBlockAndWait:block];
}
Conflicting parameter types in implementation of 'performBlock:': 'void (^ _Nonnull __strong)(void)' vs 'void (^__strong _Nonnull)()'
```

**Comment by mentrena** [comment]
Thanks, I believe these issues have been addressed, but let me know if I missed anything.
