### ISSUE TITLE
New case about CKErrorUserDeletedZone

### ISSUE THREAD

**Issue by shenmueXVI** [mentrena/SyncKit#27]
Hello, sometimes user delete icloud data from general device settings. After that action I call synchronizeWithCompletion and I have error CKErrorUserDeletedZone. I call eraseLocal or eraseRemoteAndLocalDataWithCompletion then again repeat synchronizeWithCompletion and I again have CKErrorUserDeletedZone - and so endlessly.

I study code in library and I think in setupCustomZoneWithCompletion to need add condition instead 

`else if (error.code  == CKErrorZoneNotFound && ... to else if ((error.code  == CKErrorZoneNotFound || error.code  == CKErrorUserDeletedZone) && ...`

After that I get reinitialize and new working customZone without errors

What do you think about it?

**Comment by mentrena** [comment]
I think that's the right thing to do, I'll update soon.
Just keep in mind that, to handle the situation, you will need to call `eraseLocal`, since all the tracking metadata is now invalid.

**Comment by mentrena** [comment]
`0.5.7` includes the change. Closing here, thanks and feel free to reopen if the issue persists.
