### ISSUE TITLE
Limit exceeded error from CloudKit

### ISSUE THREAD

**Issue by Rodge73** [mentrena/SyncKit#30]
Hi 

I'm using SyncKit for synchronising a local Core Data model into iCloud. SyncKit has proven to be very stable and reliable. Great job on that.

I had one persistent issue on 1 device that was getting error due to 'Limit Exceeded'.
It turned out about 200 records were not being synced anymore after having added many records off-line. 

After investigation I could fix this issue by manually changing the default batchSize from 100 to 20. 
  static const NSInteger QSDefaultBatchSize = 20;  //WAS 100;

I noticed that SyncKit has a feature to automatically reduce the batchSize in case of LimitExceeded. 
This was clearly not working for some reason. Or maybe I don't fully get the implementation details.

              if (operationError.code == CKErrorLimitExceeded) {
                    self.batchSize = self.batchSize / 2;
                    ...

I'm using SyncKit 0.5.5.

Hopefully this is helpful for you to further improve SyncKit.

regards
Rodge

Below the (partial) stack trace:

Synchronize ERROR
Optional(<CKError 0x1c4459980: "Partial Failure" (2/1011); "Failed to modify some records"; uuid = 03CAFB05-9A39-41F8-B7C6-71ADB20B8B02; container ID = "iCloud.com.myapp"; partial errors: {
	Parent.70B5CA5C-D5EF-4CDC-AD2B-33AF95298ED6-1149-00000548904E7DEC:(QSCloudKitCustomZoneName:__defaultOwner__) = <CKError 0x1c8442e20: "Limit Exceeded" (27/2023); server message = "Database commit size exceeds limit"; uuid = 03CAFB25-9A39-41F8-B7D6-31ADB20D8B02>
	Child.E91E0362-59A3-43B8-8136-0116B2145DBB-1129-0000059A7379915C:(QSCloudKitCustomZoneName:__defaultOwner__) = <CKError 0x1c8444f80: "Limit Exceeded" (27/2023); server message = "Database commit size exceeds limit"; uuid = 03CAAB05-9A29-4BF8-B7C6-71ADB90B8B02>

**Comment by Rodge73** [comment]
As it turns out the operationError.code == 2 (CKErrorPartialFailure) is the actual error code the SyncKit library was reporting when getting the 'Limit Exceeded' error from iCloud. So leaving the  DefaultBatchsize to 100 and checking also for CKErrorPartialFailure to limit the batchSize fixes the issue as well. This however needs manual trigger of the syncing feature to restart syncing.
 
in: QSCloudKitSynchronizer.m: uploadEntitiesWithCompletion:

                //if (operationError.code == CKErrorLimitExceeded) { //ORIGINAL
                if (operationError.code == CKErrorLimitExceeded || operationError.code == CKErrorPartialFailure) { //UPDATED
                    self.batchSize = self.batchSize / 2;
                } else if (self.batchSize < QSDefaultBatchSize) {
                    self.batchSize++;
                }

**Comment by mentrena** [comment]
Ah, after updating to use `CKFetchRecordZoneChangesOperation` the errors would now be reported per record zone (even if it's using just one record zone).
I think after getting `CKErrorPartialFailure` it should still be possible to inspect the inner error to confirm it's a  `CKErrorLimitExceeded`.
I'll update the code, thanks.

**Comment by mentrena** [comment]
Hi @Rodge73 , I've published 0.5.6 to fix this.
Thanks for reporting it and let me know if the issue persists.

**Comment by Rodge73** [comment]
Hi Mentrena. Sorry for the delay, but I can confirm this issue is fixed! Thanks again for your help and all the best with SyncKit!
Rodge
