### ISSUE TITLE
carthage build downloads only SyncKitCoreData

### ISSUE THREAD

**Issue by joelkraut** [mentrena/SyncKit#33]
When I add SyncKit to my Cartfile and `carthage update`, I see `Downloading SyncKit.framework binary at "0.5.7"` and end up with only the SyncKitCoreData files. When I run `carthage update --no-use-binaries`, I get a build error on the `SyncKitRealmOSX` scheme. The error log says things like "/Users/manuel/Documents/Apps/SyncKit/SyncKit/Classes/QSSynchronizer/SyncKitLog.h", leading me to believe that there are some absolute file references in there. Anyway, `carthage update SyncKit --no-use-binaries --platform iOS` ends up working.

**Comment by mentrena** [comment]
Thanks, should hopefully have been fixed with `0.5.8`. Let me know if the issue still happens.
