### ISSUE TITLE
restore from iCloud backup

### ISSUE THREAD

**Issue by shenmueXVI** [mentrena/SyncKit#36]
Hi, I think there is problem. For example: I use app on device 1 with SyncKit and CoreData informartion with icloud. Device 1 has SyncKit deviceIdentifier "abcdefguniqid". Next, on device 1 on settings I press iCloud Backup Now. Next, I take Device 2 and setup restore icloud back up data from Device 1. Next, Device 2 has same (copy) userDefaults and other documents, also has same (copy) deviceIdentifier as "abcdefguniqid". So Device 1 and Device 2 have the same deviceIdentifier and I think it is big problem, because Device 1 and Device 2 generate unique data, but they don't sync, because logic from SyncKit think it's one device and work uncorrectly. What do you think about it?

My opinion: SyncKit deviceIdentifier must unique on each device, but need logic generated unique deviceIdentifier without reference to the saved earlier deviceIdentifier or something else.

Does SyncKit have some logic for decide this situation?

**Comment by mentrena** [comment]
Hi, I hadn't thought of that possibility.
I added some code here: https://github.com/mentrena/SyncKit/commit/be96a440d0ecfc4a1bf3ad08695c4d3946f2fd67
to create a new device identifier if the library detects it's being run after restoring a backup. I haven't tested yet but let me know your thoughts.

**Comment by shenmueXVI** [comment]
Thank you very mouch, I am going test it

**Comment by mentrena** [comment]
Just keep in mind the app should have run at least once before the backup is made
