### ISSUE TITLE
Public Database sync

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [mentrena/SyncKit#38]
Would it be possible for you to add support for synchronising PUBLIC databases?

I am using RealmSwift for local data storage.

The use case I have is that my app has private data AND public data.

Currently I am achieving this using 2 Realms which is a nice separation but causes issues when relating data across realms.  

In my idealised world..... I would love to only require one single Realm and know that SyncKit is processing specific models to PRIVATE and other models to PUBLIC.  A big ask I know.  Maybe adding a property to specific models could detail to SyncKit how to process that model?  All that said - I'd be happy with syncing 2 Realms one for each PRIVATE and PUBLC data.

Thanks!  Keep up the good work.

**Comment by mentrena** [comment]
Hi Ian, the problem is that synchronization relies on the `CKFetchRecordZoneChangesOperation` operation, which is supported by the private and shared databases, but not by the public one, so it's not possible to ask the public database for "changes that happened since the last sync".

Instead, you still need to use some combination of `CKQuery` and fetch operations (I guess this is what you're doing already)

**Comment by ianbradbury-bizzibody** [comment]
Okay.  

Currently I'm syncing to the Realm Object Server - my goal is to migrate to CloudKit from ROS.

If I can't use SyncKit for the public data - as you suggest I'll just have to deal with that manually.  

Presumably I'll still need 2 local Realm databases, one for synced private data and another for the public data, unless there is a way to specify which models can be synced to CloudKit?

KUTGW

**Comment by mentrena** [comment]
That's right, there's a 1-1 match from Realm to Record Zone, so you would ideally keep separate realms for the private and public databases. You could put your public data in the same realm, but that would mean your public data would also be backed to the private database, and you probably don't want this unless your public data is really small...

**Comment by ianbradbury-bizzibody** [comment]
Okay.  I will take that route for the moment.

If it becomes possible to provide public DB support within Sync Kit that would be preferable - there is nothing worse than having 2 sets of sync code.

**Comment by ianbradbury-bizzibody** [comment]
What is the story regarding SHARED data?

**Comment by mentrena** [comment]
`If it becomes possible to provide public DB support within Sync Kit`

If Apple ever provide a `CKFetchRecordZoneChangesOperation` operation in the public database it would be really simple to make it work with the library. But that won't happen.

`What is the story regarding SHARED data?`

I'm working on it. It's tough.

**Comment by ianbradbury-bizzibody** [comment]
Thanks @mentrena 

(I did think the SHARED would be tough)
If you manage it - I'll be the happiest person!

Good luck.
