### ISSUE TITLE
Carthage 3.3

### ISSUE THREAD

**Issue by CoolHandLuke88** [mentrena/SyncKit#4]
**Carthage Install gives the following errors;**

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/lukemcdonald/Documents/Core/SyncKitTutorial/Carthage/Checkouts/SyncKit/Framework/SyncKit.xcworkspace -scheme SyncKitiOS -configuration Release -derivedDataPath /Users/lukemcdonald/Library/Caches/org.carthage.CarthageKit/DerivedData/SyncKit/0.3.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

**LOG Below;**

The following build commands failed:
	CompileC /Users/lukemcdonald/Library/Caches/org.carthage.CarthageKit/DerivedData/SyncKit/0.3.1/Build/Intermediates/SyncKit.build/Release-iphoneos/SyncKit.build/Objects-normal/armv7/QSOriginObjectIdentifier+CoreDataProperties.o /Users/lukemcdonald/Documents/Core/SyncKitTutorial/Carthage/Checkouts/SyncKit/SyncKit/Classes/CoreData/QSOriginObjectIdentifier+CoreDataProperties.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/lukemcdonald/Library/Caches/org.carthage.CarthageKit/DerivedData/SyncKit/0.3.1/Build/Intermediates/SyncKit.build/Release-iphoneos/SyncKit.build/Objects-normal/armv7/QSOriginObjectIdentifier.o /Users/lukemcdonald/Documents/Core/SyncKitTutorial/Carthage/Checkouts/SyncKit/SyncKit/Classes/CoreData/QSOriginObjectIdentifier.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/lukemcdonald/Library/Caches/org.carthage.CarthageKit/DerivedData/SyncKit/0.3.1/Build/Intermediates/SyncKit.build/Release-iphoneos/SyncKit.build/Objects-normal/armv7/QSRecord.o /Users/lukemcdonald/Documents/Core/SyncKitTutorial/Carthage/Checkouts/SyncKit/SyncKit/Classes/CoreData/QSRecord.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

**Comment by mentrena** [comment]
Thanks for reporting @CoolHandLuke88 . Hopefully fixed with the latest update.

**Comment by CoolHandLuke88** [comment]
thank you. love the library, Great Work Sir.
