### ISSUE TITLE
Can't share twice

### ISSUE THREAD

**Issue by LeJeko** [mentrena/SyncKit#49]
I've an issue with the SyncKitCoreDataExample and sharing feature.
If I stop a share and try to share it again, it produce this error:
(it's reproductible with the current release)

_<CKError 0x60c000257100: "Partial Failure" (2/1011); "Failed to modify some records"; uuid = B006F530-D182-4632-9AD8-44B500677AD7; container ID = "MYCONTAINERIDHERE"; partial errors: {
	Company.776B3C03-B3AF-40D4-8E43-B26B3A71607B:(QSCloudKitCustomZoneName:__defaultOwner__) = <CKError 0x60c00024f960: "Server Record Changed" (14/2004); server message = "client oplock error updating record"; uuid = B006F530-D182-4632-9AD8-44B500677AD7>
	... 95 "Batch Request Failed" CKError's omited ...
}>_

I've try to use removeShare instead of deleteShare without success....

I've found a possible explanation here: https://stackoverflow.com/questions/48391834/ckshare-server-record-changed-error but I don't know how exactly works SyncKit...

**Comment by LeJeko** [comment]
Hi again... sorry I had an local cache issue, employees appears well after re-accept the share.
So just adding the line with savePolicy solve the issue!

**Comment by mentrena** [comment]
Thanks for the report. The problem had to do with the cached record for a shared object not getting updated after its share was removed using UICloudSharingController, `0.6.4` should fix the problem but please reopen if it still persists.
