### ISSUE TITLE
<SyncKit/QSCloudKitSynchronizer+CoreData.h> is not found in example project

### ISSUE THREAD

**Issue by Dirk-** [mentrena/SyncKit#5]
I tried to build SyncKitCoreDataExample, but got this error:

/Users/user/path/SyncKit/Example/SyncKit/QSAppDelegate.m:10:9: 'SyncKit/QSCloudKitSynchronizer+CoreData.h' file not found

![bildschirmfoto 2017-05-29 um 15 58 30](https://cloud.githubusercontent.com/assets/7225580/26552784/f5252096-4488-11e7-9e76-2f7922e12f9d.png)

That file is in /Users/user/path/SyncKit/SyncKit/Classes/CoreData/QSCloudKitSynchronizer+CoreData.h

How do I import it?

**Comment by mentrena** [comment]
Hi @Dirk- , did you run `pod install` on the Example directory?

**Comment by Dirk-** [comment]
Hi @mentrena, yes, I did. First I got

> The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


due to missing Podfile.lock and Manifest.lock

I had to run `pod deintegrate` and `pod install` to get rid of this error. Then the build process stopped with the error above.

**Comment by mentrena** [comment]
I just downloaded a copy of the repository, ran `pod install` and was able to compile fine 😕
Could you provide the version you're using for cocoapods, Xcode, etc ?
Could you also try with a fresh copy?

**Comment by Dirk-** [comment]
I tried a fresh copy today (cloned it again). I ran pod install which went successfully. I then prepared the project for my developer account and tried to compile. Build failed with the shell script invocation error I had before:

> diff: /Podfile.lock: No such file or directory
> diff: /Manifest.lock: No such file or directory
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

This time I was not able to resolve this issue by running `pod deintegrate` and `pod install`. I also ran `pod repo update`, to no avail. I restarted Xcode several times, did "Clean" and "Clean Build Folder...".

Versions I use:
cocoapods: 1.2.1
Xcode: 8.3.2
macOS: 10.12.5

I also tried it on another Mac (same system configuration). It compiled fine, without the 'SyncKit/QSCloudKitSynchronizer+CoreData.h' error, but it could not link. I will post the error message when I get home.

Thank you for looking into that...

**Comment by Dirk-** [comment]
This is the linker error I get on my Mac at home:

![bildschirmfoto 2017-05-30 um 18 37 53](https://cloud.githubusercontent.com/assets/7225580/26594249/3a328e1a-4567-11e7-9354-73c6021926dc.png)

I don't know where this comes from.

**Comment by mentrena** [comment]
Still can't reproduce, but I just made a change to the workspace file, could you try with it?
Here's what I do:
- run `pod install`
- open workspace
- at this point, SyncKitCoreDataExample should already build.
- change app id
- set development team
- in Capabilities, enable iCloud and CloudKit and make sure it uses the correct iCloud container.
- in the app delegate, use the right iCloud container for the synchronizer.
- now I can run on the simulator or device and see my content from iCloud.

**Comment by Dirk-** [comment]
I followed the steps exactly and it works!

I have to admit I always opened `SyncKitCoreDataExample.xcodeproj` directly, not the workspace. Maybe this was a problem source, too. I do not have any experience with cocoapods, sorry for that.

Now I can try the lib, thanks a lot!
