### ISSUE TITLE
Multiple QSParentKey?

### ISSUE THREAD

**Issue by szemian** [mentrena/SyncKit#51]
Hi,

I have a doubt: how do I handle a NSManagedObject that has two parents? 

In your sharing example (https://github.com/mentrena/SyncKit/wiki/Sharing), if I introduced State NSManagedObject, and Address has a relationship to State, how can I handle the issue of Address having two parents (Employee and State)?  

Thanks.

**Comment by mentrena** [comment]
Hello, 

An object cannot have more than one parent in CloudKit, it is for you to design your model accordingly and decide what the parent entity should be. In your example, why would you want Address to have two parents?

**Comment by szemian** [comment]
Hi,

Actually it is not really two parents, but having more than two relationships (CKReference). I am imagining how it will handle if "Address" has multiple relationships to other Entity like "Town", "State", "Country", and when I share a CKRecord of a "Company", will it share the non parents relationship of "Address" or they are left behind?

**Comment by mentrena** [comment]
I see, in that case they would be left behind, as you say.

If different Address objects reference the same State, then it wouldn't make sense to say that either address is the parent of the State entity. You would get to reuse the State entity but it wouldn't get shared when you share one of the companies.
An alternative would be keeping one State instance per Address, so you can clearly assign the address as the state's parent, or making State a field of Address.

**Comment by szemian** [comment]
Keeping the State instance per Address will defeat the purpose of normalising the data, might as well as keeping it in Address as String instead of CKReference.

Thanks for your clarification. I guess I will have to denormalise my data in order to use CloudKit sharing.
