### ISSUE TITLE
QSChangemanager missing CoreData Sync

### ISSUE THREAD

**Issue by spotlessicode** [mentrena/SyncKit#53]
Hi, 

I've just updated from 0.5.8 to 0.6.5 pod, but I checked, and from 0.6.0 the QSChangeManager.h  is missing. It causes more problems - see attachements. 
I can not find any references to this update or at Core data migration in the readme.

Did you intent to remove it, and there is a new way to check the changes, or it was a coincidence? If the latter, could you put it back? 

Thank you,

Eva

![screenshot 2018-10-09 at 16 18 16](https://user-images.githubusercontent.com/9674092/46676170-3fe6c000-cbe0-11e8-8b9d-9f6da3e6490c.png)
![screenshot 2018-10-09 at 16 16 29](https://user-images.githubusercontent.com/9674092/46676182-45dca100-cbe0-11e8-923a-6a0fc1cf8534.png)
![screenshot 2018-10-09 at 16 17 34](https://user-images.githubusercontent.com/9674092/46676198-4bd28200-cbe0-11e8-8045-bb041245df40.png)

**Comment by mentrena** [comment]
Hi, the file was renamed to QSModelAdapter.h , have you tried doing a clean build?

**Comment by mentrena** [comment]
Ah, the screenshots are from your code. 0.6.0 renamed several things when it added support for sharing, you might have to update your code.
I'll close here but feel free to reopen if you have more questions.

**Comment by spotlessicode** [comment]
Hello, 

Thank you for the fast response, I solved, but just let you and others know:

2 things are missing:

1. QSModelAdapter id from QSCloudKitSynchronizer.h - it needs for migration / changes to connect synchronizer with QSCoreDataAdapter.h
Solution: add line to QSCloudKitSynchronizer.h
`@property (nonatomic, strong, readonly) id<QSModelAdapter> changeManager;`

2. Watch OS subcription part is missing from QSCloudKitSynchronizer.h and m file as well. .. I have to check, if it needs, or changed.. but looks like good. 
```
#if !TARGET_OS_WATCH

/**
 *  Creates a new subscription with CloudKit so the application can receive notifications when new changes happen. The application is responsible for registering for remote notifications and initiating synchronization when a notification is received. @see `CKSubscription`
 *
 *  @param completion Block that will be called after subscription is created, with an optional error.
 */
- (void)subscribeForUpdateNotificationsWithCompletion:(void(^)(NSError *error))completion;

/**
 *  Delete existing subscription to stop receiving notifications.
 *
 *  @param completion Block that will be called after subscription is deleted, with an optional error.
 */
- (void)deleteSubscriptionWithCompletion:(void(^)(NSError *error))completion;

/**
 *  Returns identifier for a registered `CKSubscription` to track changes.
 */
@property (nonatomic, readonly) NSString *subscriptionID;

#endif
```
Anyway, just changes ChangeManager to Adapter at every part of my code  (delegate, import, and even calls) could solve the problems. 

After these could I run my App on real device. I'll test in these days and let you know, if there is anything else with CoreData-Watch-SyncKit. 
![screenshot 2018-10-09 at 17 48 00](https://user-images.githubusercontent.com/9674092/46682760-c30f1280-cbee-11e8-8e33-721c0928feb8.png)

![screenshot 2018-10-09 at 17 59 33](https://user-images.githubusercontent.com/9674092/46682782-d0c49800-cbee-11e8-96cd-c982f1952073.png)

Eva

**Comment by mentrena** [comment]
You probably shouldn't make any changes to the files in the library, otherwise you will lose them next time you do a pod update and it will just make it harder for you to maintain your project.

> QSModelAdapter id from QSCloudKitSynchronizer.h - it needs for migration / changes to connect synchronizer with QSCoreDataAdapter.h
Solution: add line to QSCloudKitSynchronizer.h

The `modelAdapters` array has what you need. 

> Watch OS subcription part is missing from QSCloudKitSynchronizer.h and m file as well

Code to handle subscriptions is now in QSCloudKitSynchronizer+Subscriptions.swift

If you needed to know more about the internals of the library there's more info in the [wiki](https://github.com/mentrena/SyncKit/wiki/Architecture)

**Comment by spotlessicode** [comment]
Thank you! 
Yes, but it's not so easy, if you have already those in your project. I needed to figure it out step by step, where what changed and why. 

Do you think is a `modelAdapters objectAtIndex:0` a good approach? just because of this is a private database so there is no more adapters, only one, and I can't call tracking primarykey on arrays of course, so I need an ID. Here is what I mean: 

instead of this
```
QSCoreDataAdapter *cdcm =(QSCoreDataAdapter *)self.synchronizer.changeManager;
[cdcm updateTrackingForObjectsWithPrimaryKey];
```
with the Adapters Array:
```
QSCoreDataAdapter *cdcm =(QSCoreDataAdapter * )[self.synchronizer.modelAdapters objectAtIndex:0];
 [cdcm updateTrackingForObjectsWithPrimaryKey];
```
I've already found the Subscriptions too, just need more time at first to go through all the changes.
Thanks for the Wiki, we will need the share database as well, if we reach that point once :) As I see all update a great job form you again!

Really thanks for your time to help me with it !

**Comment by mentrena** [comment]
> Do you think is a modelAdapters objectAtIndex:0 a good approach?

Can't say I like it, but I do `modelAdapters.firstObject` at the moment 😅
It makes sense for the private database synchronizer.

By the way, `updateTrackingForObjectsWithPrimaryKey` was added more than a year and a half ago, I'm curious how likely you think it is your app will actually need it –just to help me understand whether this kind of backwards-compatible code is still useful.

**Comment by spotlessicode** [comment]
Yes firstObject of course :) I need it. 
This updateTrackingForObjectsWithPrimaryKey was needed to update databases at new App version, if they have no primaryKey earlier, (in my case we can’t use the name property, because they can create goals and tasks with same name so we had to change the primaryKey to UUID).. maybe there are 5-14 devices based itunesconnect analytics with App version with the very old database,  so I would like to use this safety update code, for the next launch. We didn’t have time for Purp App in the last 3 months, but till July we built more new features, and the core data model was growing as well, with CloudKit development database already changed.. so it would be better, if after this 3.0 Launch,  we will check the App versions at the users again, try to force update… and at 3.1-3.2 Usability improvements, we will clean those codes as well. 
so please don’t remove them yet. ;)

Thank you!
