### ISSUE TITLE
[QSCoreDataAdapter saveToken:] wrong thread

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#54]
It looks like, that saveToken: method is using wrong thread when modifying QSServerToken object. As far as I know managedObjects modifications should be done in thoeir managedObjectContexts threads. I recently updated SyncKit and during server token transfer (from older commit/system) I got multithreading violation. I run app "with -com.apple.CoreData.ConcurrencyDebug 1" flag. It seems to me that qsToken.token = [NSKeyedArchiver archivedDataWithRootObject:token] should be performed in self.privateContext thread (performBlock: ... ). Unless I am doing something wrong.

**Comment by BlixLT** [comment]
Not sure if I should create a new issue, I guess I will write it here as a comment for now. Another multithreading violation happens during deleteDataStore. xcode stops on the line [self.managedObjectContext reset]; So, it seems to me that this line also should be called in the self.managedObjectContext thread.

**Comment by mentrena** [comment]
Fixed in 0.6.6, thanks!
