### ISSUE TITLE
Pod install

### ISSUE THREAD

**Issue by KingOlami** [mentrena/SyncKit#56]
using `pod 'SyncKit/Realm', '~> 0.6.4'`gives and error in my terminal and I cannot install

`Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "SyncKit/Realm":
  In Podfile:
    SyncKit/Realm (~> 0.6.4)

None of your spec sources contain a spec satisfying the dependency: `SyncKit/Realm (~> 0.6.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
`

**Comment by mentrena** [comment]
From the other issue you've opened I guess you were able to run `pod install` in the end, though you forgot to close this issue 👍

**Comment by MilesV64** [comment]
What was the fix for this? I'm getting the same error with version 0.7.4
