### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by KingOlami** [mentrena/SyncKit#58]
I tried to follow the example and implement a similar code but whenever i click on the share button, I get an error saying `Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value` on the 
` 
// MARK: - Sync
    
    func synchronize(completion: ((Error?)->())?) {
        
        showLoading(true)

        synchronizer.synchronize { [weak self] (error) in // ERROR LINE
......
` any reason for this error?

**Comment by KingOlami** [comment]
If i re run the application, I get an error in the RealmSwiftAdapter on line 238

```
    func realmObjectClass(name: String) -> Object.Type {
        
        if let objClass = NSClassFromString(name) {
            return objClass as! Object.Type
        } else {
            let namespace = Bundle.main.infoDictionary!["CFBundleExecutable"] as! String
            return NSClassFromString("\(namespace).\(name)") as! Object.Type //238
        }
    }
```

great job you are doing kindly assist by pointing me in the right direction

**Comment by mentrena** [comment]
Hi @KingOlami ,

Just a quick check: What's the configuration for your Realm? Do you specify the classes that it should handle? [Realm wiki](https://github.com/mentrena/SyncKit/wiki/Realm)

```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.objectClasses = @[MyClass.class, MyOtherClass.class];
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
```

**Comment by KingOlami** [comment]
this is the way I wrote the code because I have separate functions holding different realm instances.

```
 private var database:Realm
    static let instance = CategoryFunctions()
    
    var categoryArray: Results<CategoryModel>?
    var notificationToken: NotificationToken!
    let category = CategoryModel()
    
    private init() {
        database = try! Realm()
    }
    
    
    //MARK:- Add Category Function
    func addData(object: CategoryModel)   {
        try! database.write {
            database.add(object)
        }
    }
```

I have a class specifically for creating categories.

**Comment by mentrena** [comment]
Right, so you are creating the realm with the default configuration, which means that your realm schema will include all classes in the project that inherit from RealmObject. SyncKit uses its own Realm classes to store metadata about your model classes, so you don't want your own Realm to include those classes.

You will need to do as the wiki says and create a Realm configuration that specifies which classes your Realm should handle:
```swift
var configuration = Realm.Configuration()
configuration.schemaVersion = 1
configuration.objectTypes = [YourClass1.self, YourClass2.self]
...
var realm = try! Realm(configuration: configuration)
```

Other than the wiki, the [example project for RealmSwift](https://github.com/mentrena/SyncKit/tree/master/Example/RealmSwift) also shows how to do this. Please use the wiki and the example project for reference.

**Comment by KingOlami** [comment]
I did it the same way that is why I am wondering why I am getting an error since I followed the example

**Comment by mentrena** [comment]
The code you posted doesn't look the same though. Your code did:
```swift
...
private init() {
        database = try! Realm()
    }
...
```

**Comment by KingOlami** [comment]
I changed it to 

```...
private init() {
        database = try! Realm()
    }
...
```

and I am still getting the same error

**Comment by sskjames** [comment]
I got a similar exception when I create a Realm without specifying any configuration. It was resolved by following this suggestion.

> Right, so you are creating the realm with the default configuration, which means that your realm schema will include all classes in the project that inherit from RealmObject. SyncKit uses its own Realm classes to store metadata about your model classes, so you don't want your own Realm to include those classes.
> 
> You will need to do as the wiki says and create a Realm configuration that specifies which classes your Realm should handle:
> 
> ```swift
> var configuration = Realm.Configuration()
> configuration.schemaVersion = 1
> configuration.objectTypes = [YourClass1.self, YourClass2.self]
> ...
> var realm = try! Realm(configuration: configuration)
> ```
> 
> Other than the wiki, the [example project for RealmSwift](https://github.com/mentrena/SyncKit/tree/master/Example/RealmSwift) also shows how to do this. Please use the wiki and the example project for reference.

Hope this might help someone who is getting started with SyncKit.
