### ISSUE TITLE
Memory leak in QSFetchZoneChangesOperation.swift

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#59]
When running with Instruments, they show quite a lot memory leaks. As far as I can tell, they originated from QSFetchZoneChangesOperation.swift. It seems that QSFetchZoneChangesOperation has a strong pointer to CKFetchRecordZoneChangesOperation and CKFetchRecordZoneChangesOperation has a strong pointer to QSFetchZoneChangesOperation in one (or several) of the blocks (completions). And ARC cannot release them. If I add
` self.operation = nil`
at the end of operation.fetchRecordZoneChangesCompletionBlock:
```
                if let error = operationError {
                    self.finish(error: error)
                } else if higherModelVersionFound {
                    self.finish(error: NSError(domain: QSCloudKitSynchronizerErrorDomain, code: QSCloudKitSynchronizerErrorCode.higherModelVersionFound.rawValue, userInfo: nil))
                } else if self.isCancelled {
                    self.finish(error: NSError(domain: QSCloudKitSynchronizerErrorDomain, code: QSCloudKitSynchronizerErrorCode.cancelled.rawValue, userInfo: nil))
                } else {
                    self.completion(self.zoneResults)
                    self.finish(error: nil)
                }
                self.operation = nil
```
then Instruments don't show leaks anymore during fetching changes from cloudkit. Not 100% sure if a pointer to operation is still needed there (my guess is that it is not). So, if not, I suppose that could be a fix for these leaks.

**Comment by mentrena** [comment]
Fixed in 0.6.7
Thanks!
