### ISSUE TITLE
SyncKit/SyncKit-Swift.h file not found

### ISSUE THREAD

**Issue by kiwi07** [mentrena/SyncKit#76]
Hello,

Please help me fix the issue "fatal error: 'SyncKit/SyncKit-Swift.h' file not found".
I installed the SyncKit using cocoapods for an objective c project:
platform :ios, '11.0'
use_modular_headers!
target 'myproject' do
pod 'SyncKit/Realm' 
end

Please take a look at the capture image.
http://prntscr.com/npvz8b

**Comment by mentrena** [comment]
Hi @kiwi07,

You need to use `use_frameworks!` in your Podfile. The library uses some Swift code so it must be imported into your project as a framework, not a static library.

**Comment by kiwi07** [comment]
Hi @mentrena,

thank you for your response. However, if I use the use_frameworks! in podfile, another objective-c pods could not be installed. Can we use use_frameworks! for just a specific pod like SyncKit/Realm?

**Comment by mentrena** [comment]
Unfortunately it does not seem like Cocoapods supports using `use_frameworks!` for only some of your pods.
Most libraries should support being imported as frameworks, even if they're ObjC projects, so I would check if there's a newer version of that other library you're using.
If that doesn't work, I guess you would have to add some of the libraries manually to your project –or perhaps through Carthage if that's an option. If you go with Carthage, keep in mind SyncKit doesn't get imported nicely at the moment so you still need to open the project and manually build to obtain the .framework file.
