### ISSUE TITLE
<CKError 0x170059b30: "Server Record Changed" (14/2004); server message = "client oplock error updating record">

### ISSUE THREAD

**Issue by jackieliujcl** [mentrena/SyncKit#8]
sync error, got this issue after change some value of a RLMObject. And  I run the demo app, same issue.

```
<CKError 0x170059b30: "Server Record Changed" (14/2004); server message = "client oplock error updating record">
```
Could you please help?
It's a great library ! Thank you!

**Comment by mentrena** [comment]
Hi @jackieliujcl , I've just published 0.4.5 to fix Realm issues, could you try with that and let me know?
Thanks
