### ISSUE TITLE
Missing return after calling completion with already syncing error

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#82]
I think there is a bug in the 0.7.4 version: CloudKitSynchronizer.swift : 149 line. 
After calling completion there is no return from the method. I think there should be. If you think there shouldn't, then something else is wrong - targetImportContext becomes reset and destroyed during one of completions, but other sync process is still in progress and crashes when try perform block with that destroyed context.

**Comment by mentrena** [comment]
You're right, that totally should be a `guard/return`

**Comment by mentrena** [comment]
Fixed with 0.7.5
