### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by shekunsky** [mentrena/SyncKit#83]
Hi!
I'm updated to the version 0.7.4 and started receive an error
"Fatal error: Unexpectedly found nil while unwrapping an Optional value" in the file RealmSwiftAdapter.swift line 748 (for property in object!.objectSchema.properties).
Before this i successfully used version 0.6.11 and sync worked fine.
I used a config for realm with list of objects. And this was not changed...

**Comment by shekunsky** [comment]
Resolved by deleting '**CloudKit**' folder and sync files in '**Application Support**' folder...

**Comment by mentrena** [comment]
Hey @shekunsky , sorry I never got around to check this. 
I believe I should still avoid the force unwrap on the line you pointed out, so thanks for that, I'll try to do that soon. Although in theory if the object doesn't exist any more in the Realm then there shouldn't be a pending upload for it so I'm still puzzled about that 🤔 
Anyway, thanks!
