### ISSUE TITLE
isServerRecordChangedError check (partial error) bug

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#84]
CloudKitSynchronizer+Sync.swift, line 106:
`            
let errorsByItemID = error.userInfo[CKPartialErrorsByItemIDKey] as? [String: NSError],
`
I think it should be (at least the error I am getting sometimes is not String : NSError) :
`            
let errorsByItemID = error.userInfo[CKPartialErrorsByItemIDKey] as? [CKRecord.ID: NSError],
`
otherwise errorsByItemID is nil

**Comment by mentrena** [comment]
Fixed with 0.7.5
