### ISSUE TITLE
Invalid keypath passed to setPropertiesToFetch:

### ISSUE THREAD

**Issue by FrederickGeek8** [mentrena/SyncKit#86]
Hello! I am a bit new to Core Data usage, so I'm not sure if this is necessarily something wrong with the library or with my implementation, however, the issue goes away if I bypass the SyncKit code. The error in question is `Invalid keypath Bookmarks passed to setPropertiesToFetch:`. For context, my Entity & CloudKit record type is called `Bookmarks`. The error breaks on the `privateSynchronizer` line, specifically on line 173 of `CoreDataAdapter.swift` from SyncKit

My SyncKit code:
```swift
if FileManager.default.ubiquityIdentityToken == nil {
    synchronizer = nil
    return
}


let appDelegate = UIApplication.shared.delegate as! AppDelegate
synchronizer = CloudKitSynchronizer.privateSynchronizer(containerName: "iCloud.net.nerd.Read-arXiv", managedObjectContext: appDelegate.persistentContainer.viewContext)

if let zoneID = synchronizer?.modelAdapters.first?.recordZoneID {
    synchronizer?.subscribeForChanges(in: zoneID) { (error) in
        if error != nil {
            print("Error: \(error!)")
        }
    }
}
```

I don't think it's relevant but here is my [CoreDataClass](https://github.com/FrederickGeek8/Read-arXiv/blob/master/Read%20arXiv/Bookmarks%2BCoreDataClass.swift) and [CoreDataProperties](https://github.com/FrederickGeek8/Read-arXiv/blob/master/Read%20arXiv/Bookmarks%2BCoreDataProperties.swift). Other code in my project can be found on that repo.

**Comment by mentrena** [comment]
Hi @FrederickGeek8 ,
I believe the problem has to do with your implementation of `primaryKey()`. In that function you must return the name of a property in the class that will have a unique value for each instance of that class.
So for example, if you had a list of Book objects, and Book had a property called `bookID`, you would want to do:
```swift
public static func primaryKey() -> String { return "bookID" } 
```

In your case, maybe that would be `articleID`? Or if that field has a different purpose, you might have to add a new property to Bookmarks called `bookmarkID`.
Take a look at QSCompany and QSEmployee classes in the example project.

**Comment by FrederickGeek8** [comment]
Ah yes, my bad. I thought that the `primaryKey` function would for some reason return the primary key of the entry, not the attribute name.
