### ISSUE TITLE
Xcode 11 support

### ISSUE THREAD

**Issue by paulstelzer** [mentrena/SyncKit#87]
At the moment SyncKit is not working when building with Xcode 11 (Swift Compiler 5.0.1 vs Swift Compiler 5.1). Can you give me some information if this will be supported soon?

**Comment by mentrena** [comment]
Hi Paul,
Can you provide more details? I can build the sample project using Xcode 11 and Swift 5.1.

**Comment by paulstelzer** [comment]
I think I made something wrong - it's working without problems ;)

**Comment by mentrena** [comment]
Cheers :)
