### ISSUE TITLE
Transformable attribute handling with no valuetransformername

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#88]
I have just noticed that after rewroting to swift, Transformable attribute handling has changed. There is no more "else" part when valuetransformername is not set. In the previous (objective-c) version in that case value was being transformed (coded/decoided) using NSKeyedArchiver and NSKeyedUnarchiver. Is it a bug or did you decide to stop supporting such attributes? Because now, if there is no valuetransformername set, original object (in my case NSArray of NSDictionaries) is being set as one of the CKRecord properties, but NSDictionary does not conform to CKRecordValue protocol and I am getting an exception about it when trying to save such CKRecord to cloudkit). Is it a bug or you missed it when rewrote SyncKit to swift 5?

**Comment by mentrena** [comment]
I think it was an error, fix is here: https://github.com/mentrena/SyncKit/pull/89

**Comment by BlixLT** [comment]
Thanks. Just wondering, do you want some feedback from me or somebody else before merging PR into master? Or are you still thinking wether to merge this fix or not?

**Comment by mentrena** [comment]
I'll merge soon, but I'll probably add an extra test before.

**Comment by mentrena** [comment]
Fixed in 0.7.6
