### ISSUE TITLE
Sharing: changes made to accepted object are being overwritten by CloudKit

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#90]
Not sure if the sync (operations) flow is incorrect (especially in the shared db), but I am experiencing problems when making changes to accepted object, that is shared by another owner (even with your sample project). As I see by default your sample project's publicPermission is .readOnly, so I changed it to readwrite to test it (CompanyPresenter.swift, 119 line), then create a new company (lets say Company1), share it and then accept it on a device with different cloudKit account. On that acceptor's device create a new Employee in that accepted shared company "Company1", lets name it Employee1, synchronise, everything is good so far - owner of a Company1 receives the change and Employee1 successfully appears there. 
But now lets try renaming that Employee, lets say to NewEmployee on the second device (device that accepted Company1). Synchronise and the old name Employee1 is being received from CloudKit and applied before we upload our change instead.
As far as I can tell the problem is that after making changes to the accepted object (Company or its childs - Employees), during updateTokens() method FetchDatabaseChangesOperation returns an empty changedZoneIDs array (therefore no change token for the latest change is being returned) and new change token is not being saved (cached) locally for that shared record zone. Because of that, when you make later change and provide not the latest change token, during fetchChanges you receive that old change and it is being applied to the local object (the old name Employee1 is being set (and it overwrites the latest change - NewEmployee) locally and the latest made change is being lost).

For testing purposes I tried performing updateTokens() in the shared database after some delay, smth like:
```
DispatchQueue.main.asyncAfter(deadline:DispatchTime.now() + X) {
self.updateTokens()
}
```
where X is ~2-4 (seconds), then I noticed that everything works as I would expect - FetchDatabaseChangesOperation returns changedZoneIDs with 1 zone where the change was made and the latest update token is successfully updated.
However, I doubt that such delay is a good fix as smth else might happen during it (more changes, etc.). 
So, the question is - have you tried editing accepted objects. If you have tried, then do similar things happen to you or am I doing something wrong?

**Comment by BlixLT** [comment]
Maybe another possible fix would be - remembering zones that you pushed changes during uploadChanges method and add such zones in the FetchDatabaseChangesOperation's completion handler. (append these zone ids to the changedZoneIDs array even if it is empty). I am not 100% sure, but I think this also worked when I tried to find a fix for this bug. RecordZone has change token, but FetchDatabaseChangesOperation incorrectly does not return that zone (in time?). 
But maybe you will have other insights. I suppose SyncKit should allow editing accepted shared objects from other owners.

**Comment by mentrena** [comment]
Maybe just ignoring the record that was uploaded by the same device would fix the issue too, so even if the second device doesn't manage to update its token for the shared record zone, because of CloudKit timing issues, next time a sync happens it won't overwrite the local data with the record it had just uploaded.
I pushed the fix to the fixes PR and it seems ok so far, but I need to do a bit more testing.
