### ISSUE TITLE
NSFetchRequest should not include subentities

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#91]
By default NSFetchRequest includes subentities and it causes incorrect behaviour. For example during performInitialSetupIfNeeded, objects of subentity will be fetched twice (when fetching parent entity, and when fetching original entity) and therefore uploaded twice. So, I think at least NSFetchRequest used in performInitialSetupIfNeeded should exclude subentities:
`fetchRequest.includesSubentities = false`
I guess all NSFetchRequest that target targetManagedObjectContext should always exclude subentities, at least I cannot think of the case where it would be needed.

**Comment by mentrena** [comment]
Fixed in 0.7.7
