### ISSUE TITLE
handling CKErrorChangeTokenExpired

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#92]
Not sure how 100% reproduce/simulate such case, but I see that there is no such error handling in the framework. As far as I can find in the forums (and documentation: "/*! The previousServerChangeToken value is too old and the client must re-sync from scratch */"), you have to resync from scratch. So, probably resetting change token and re-syncing might be enough in most cases. I was able to reproduce/simulate it by saving some old store token to file, then syncing with cloudkit several times, then editing QSSyncStore with sqlite editor (sqlite3) and force-writing that old change token, smth like:
to save to file:
```
select writefile('test.blob', ztoken) from zqsservertoken;
```
and then rewrite cached token:
```
update zqsservertoken set ztoken = readfile('test.blob');
```
Then I made a change in cloudkit dashboard and began getting server change token expired message. (cannot tell exact steps, but it was something like that). Without any fix, when such error appears, sync no more works and always ends with CKErrorChangeTokenExpired. So, my suggestion would be, smth like that (in the fetchZoneChanges method):
```
                    if let resultError = result.error {
                        error = resultError
                        if (error as! CKError).code.rawValue == CKError.changeTokenExpired.rawValue {
                            debugPrint("changeTokenExpired for zoneID: ", zoneID, ", error: ", error, "will reset change token")
                            adapter?.saveToken(nil)
                            self.activeZoneTokens[zoneID] = nil
                        }
                        break
                    }
```
What are your thoughts? As I said not sure when exactly such error might happen with "normal usage", but I suppose it can eventually and without any handling there will be no chance to fix sync (well other than disconnecting and connecting again I suppose).

**Comment by mentrena** [comment]
What if:

Client A is up to date.
Server receives instruction to delete some records by Client B.
Client A makes local changes to records deleted in server.
Client A tries to sync and gets `changeTokenExpired`

At that point, if we just reset the token and let it sync, the library would download all the records currently in the server and then try to upload any changes, which includes changes to records that don't exist in the server now, so the operation would fail. 
(That's assuming that using a nil token does not return record deletions, as in, the new sync doesn't return the entire change history but only the changes that go from a clean state to the current server state)

Maybe the right way to handle this would be to delete all local data and then re-create from the server by doing a fresh sync? That would have to be handled outside SyncKit though, in the app domain, by using `synchronizer.eraseLocalMetadata` then creating a new synchronizer to start from scratch. What do you think?

**Comment by BlixLT** [comment]
Looks like you know more about this error, so I will agree with you. I tried using your flow to get changeTokenExpired error
```
Client A is up to date.
Server receives instruction to delete some records by Client B.
Client A makes local changes to records deleted in server.
Client A tries to sync and gets changeTokenExpired
```
but I got "unknown item error" instead (when trying to make a change to ckrecord, that was deleted in cloudkit). 

Anyway, maybe in some cases changeTokenExpired error will be returned. What I don't like with a recreating synchronizer approach is that very likely changeTokenExpired occurred only in one of the zones (ModelAdapter) that is being tracked by this synchronizer, but recreating it will recreates all ModelAdapters for all zones for hat synchronizer. (while private synchronizer has only 1 ModelAdapter (tracked zoned), but I think shared synchronizer might have several). 
On the other hand, I suppose such changeTokenExpired should be very rare, so probably it is acceptable.

**Comment by mentrena** [comment]
Following up on this. I should have suggested `ModelAdapter.deleteChangeTracking()`, then removing that model adapter from the synchronizer instead.
That would mean that next time changes are detected in the record zone, the synchronizer would ask its model adapter provider for a new adapter, and synchronization would begin for that record zone.
However, that would require some changes to take place in the record zone, since the synchronizer would still be using the same database token, so it might not work until another device uploaded changes. To fix that, I'm adding a `resetDatabaseToken` function to the synchronizer, to make the synchronizer detect all record zones in the database.

**Comment by mentrena** [comment]
The sample project in `0.7.9` shows a possible way to handle this error, by disconnecting the synchronizer. A new one can then be created to sync from scratch 👍

**Comment by aehlke** [comment]
This one was a big surprise to run into without documentation on it. I disagree that a solution is to require user interaction

**Comment by aehlke** [comment]
IceCream handles it this way: https://github.com/caiyue1993/IceCream/blob/5ee39fd6a4ed1b2f020262fcf5c74acb068fa6f7/IceCream/Classes/PrivateDatabaseManager.swift#L37-L62 I'm cloning this behavior into my BigSyncKit fork: https://github.com/lake-of-fire/BigSyncKit

**Comment by aehlke** [comment]
How's this? Still figuring out how to test after running into it only once. https://github.com/lake-of-fire/BigSyncKit/commit/3d3f70449c7ea1f364559bf98768e55d2cc5dedc
