### ISSUE TITLE
synchronizer.eraseLocalMetadata or CoreDataAdapter.deleteChangeTracking bug/incomplete implementation

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#93]
I think `CoreDataAdapter.deleteChangeTracking` (or `synchronizer.eraseLocalMetadata`, that calls `CoreDataAdapter.deleteChangeTracking` in it) is incomplete or I am using it wrongly:
`deleteChangeTracking` "destroys" privateContext, but if that CoreDataAdapter is still alive, it continues observing targetContext (that it registered in its init method). When something changes in targetContext, CoreDataAdapter tries to call privateContext.performBlock, but because there is no privateContext anymore, it crashes. So, should something else be called before/after deleteChangeTracking to avoid this crash? Or maybe targetContext observation should be removed also. You suggested `synchronizer.eraseLocalMetadata` as a solution for #92, but just calling `synchronizer.eraseLocalMetadata` leads to a crash when change happens in the targetContext. 
It can be easily reproduced in the sample project - for example change SettingsViewController's didselectRow implementation to `privateSynchronizer.eraseLocalMetadata()` and then make a change to the data - add/edit/delete any company or any employee. Your input is needed.

**Comment by mentrena** [comment]
Updated `CoreDataAdapter.deleteChangeTracking` so it stops observing for changes, and added extra checks to other functions to handle the case where the identifier is nil. (https://github.com/mentrena/SyncKit/pull/99)
