### ISSUE TITLE
crash after undoing added object

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#94]
Synckit crashes when you perform undo of creation of an object - it can be reproduced in the sample app too - you just have to set undomanger to targetContext (by default on ios managedobjectcontext does not have undomanagers), then create any object (Company or Employee) and then call undomanager's undo(). After context's didsave operation that object's all properties are nil (therefore primaryKey is also nil). And during uniqueIdentifier(for:) it finds nil and crashes, because it doesn't expect nil there. 
Of course, because object does not have primary key in targetContextWillSave: and targetContextDidSave: methods, its difficult to do something about this there. But there is another notification - managedContextObjectsDidChangeNotification. While here primaryKey is also nil, but you can call `committedValues(forKeys:[primaryKey])` to receive that object's primaryKey, that was before undoing it and then mark syncedEntity as deleted accordingly. However, this object still be in notifaction's managedobjectContextDidSave: deletedObjects and when SyncKit tries to get primaryKey, it finds nil there. So, I think something should be done about allowing nil when checking primaryKey at least there. 
What are your thoughts about this?

**Comment by mentrena** [comment]
From testing this it seems that `committedValues(forKeys: [String])` is available during `NSManagedObjectContextWillSave`, so I've implemented a solution by checking whether any deletedObjects are missing their identifier at `targetContextWillSave`, then trying to get the identifier using `committedValues` and marking the entities for deletion.
From my limited testing this seems to work, let me know if it fixes the problem for you (https://github.com/mentrena/SyncKit/pull/99)
