### ISSUE TITLE
Which Errors to handle in App UI and how?

### ISSUE THREAD

**Issue by Rodge73** [mentrena/SyncKit#97]
Hi

SyckKit defines about 3 SyncErrors when syncing with iCloud CloudKit.
Still, CloudKit defines many more errors:
https://developer.apple.com/documentation/cloudkit/ckerror
In addition there can be partial errors in seeping error codes.

Do you have any guidance how to handle these CKErrors? Which one should be handled by an App, which one not.
Eg. QuotaExceeded needs to be shown to the user as he/she needs to increase iCloud storage.
ZoneNotFound would be a coding bug in my app/deployment and shouldn’t be shown to a user.

But what with the other ones, and partial errors?  Any guidance on which ones to handle in UI and which ones can be considered app-bugs?

Best,
Rodge

**Comment by mentrena** [comment]
Hi,

The library defines some errors that are specific to it, namely:
- `alreadySyncing` if you try to initiate a sync while there's an ongoing one.
- `higherModelVersionFound` when you use `compatibilityVersion` on the synchroniser, and it finds records with a higher version while downloading from CloudKit. You could use this when you want to update your Core Data model and you don't want to allow devices with the older version of your model to upload updates.
- `cancelled` if you manually cancel the sync before it finishes.

Other than those, if any errors are received from a CloudKit operation they would be passed to your completion block, so you can handle them.
The library detects `limitExceeded` to decrease the batch size for future uploads (the sync still fails though), and it can handle `zoneNotFound` to let you sync after having manually deleting a record zone (so the zone can be created again).
It also handles `serverRecordChanged` while uploading and tries to fetch those changes before trying to upload again.

Any other errors should be handled by your app, in theory, but if you think SyncKit could handle them let me know.

**Comment by Rodge73** [comment]
Thanks for your clear reply. It's useful to understand which CKErrors are being handled by SyncKit. 

The only other error I ever got that only the end-user of the app can fix was the QuotaExceeded CKError. Most other errors were 'bugs' in my code. Since SyncKit creates the schema and handles all CloudKit messaging, I think that many CKErrors wouldn't every apply. eg. 'UnknownItem', or 'ReferenceViolation'.  But I'm just not 100% sure.

Would synchoronize() return Errors that are not SyncError or CKError? If so, any idea which ones the app should handle?

**Comment by mentrena** [comment]
Yes, it could find an error when trying to save your managed object context or realm.
