### ISSUE TITLE
Update Remote Notications in the FAQ

### ISSUE THREAD

**Issue by NGromann** [mentrena/SyncKit#98]
Before subscribing for remote notifications, the user must call:
```swift
application.registerForRemoteNotifications()
```
this function is no where mentioned in the FAQ and if it is not called, the remote notifications won't work.
Also the syntax for the subscription changed to this:
```swift
synchronizer.subscribeForUpdateNotifications { (error) in 
    ...
}
```

**Comment by mentrena** [comment]
Docs have been updated and this is now mentioned [here](https://mentrena.github.io/SyncKit/configuration/#cloudkit-subscription)
